version: '3'

services:
  postgres:
    image: postgres:12.5-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "\"conference-hall\",\"conference-hall-test\""
      POSTGRES_HOST_AUTH_METHOD: trust
  firebase-emulators:
    build:
      context: ./firebase
    ports:
      - "9099:9099"
      - "9199:9199"
      - "4000:4000"
    volumes:
      - ./firebase:/app
      - ./firebase/.cache:/app/.cache/firebase/emulators/ 

